version: "3.3"

services:
  api:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  user:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: user
    depends_on:
      - nats
    networks:
      - internal

  skill:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: skill
    depends_on:
      - nats
    networks:
      - internal

  question:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: question
    depends_on:
      - nats
    networks:
      - internal

  collaboration:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: collaboration
    depends_on:
      - nats
    networks:
      - internal

  discord-bot:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: discord-bot
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
